name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - lts/iron
          - current

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
          architecture: 'x64'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Make CI
        run: make ci
